config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources :users, only: [] do
    get "history", on: :member
  end
  match 'rooms/index', via: [:post]

  post 'rooms/book'  

  resources :room_types, only: [:index] do
    member do
      get 'book'
    end
  end

  root 'room_types#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room
  belongs_to :room_type
  belongs_to :user
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_many :bookings

  validates :number, uniqueness: true

  def self.available_rooms(room_type_id, check_in, check_out)  	  	
  	Room.where("room_type_id = ? AND id not in (SELECT bookings.room_id FROM bookings WHERE bookings.room_type_id = ? AND bookings.check_in >= ? AND bookings.check_in <= ?)", room_type_id, room_type_id, check_in, check_out)
  end

  def self.booked_room_ids(room_type_id, check_in, check_out)  	 		
  	Booking.where("room_type_id = ? AND check_in <= ? AND check_in > ?", room_type_id, check_out, check_in).pluck(:room_id)  	
  end
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
	has_many :rooms, dependent: :destroy
	validates :name, uniqueness: true
	has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
         #:recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  
	# It fetches the room types in hotel 
  def index  	
  	@room_types = RoomType.all
  	respond_to do |format|
  		format.html
  		format.json {render json: @room_types }
    end
  end

  # A small page to gather the details of check in and check out from the user
  def book
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?

  # Get the details of rooms available for the dates on which user wants to check-in
  def index        
  	dates = params[:room]
  	@check_in = dates[:check_in].to_date
  	@check_out = dates[:check_out].to_date    
  	@room_type_id = params[:room_type_id]
  	if @check_out > @check_in and !(@room_type_id.nil?)
  		@rooms = Room.available_rooms(@room_type_id, @check_in, @check_out) 
      respond_to do |format|
        format.html
        format.json { render json: @rooms }
      end 		
  	else 
  		@notice = "Check In Date is more than Check Out Date!!!"
      respond_to do |format|
  		  format.html {render "room_types/book"}
        format.json { render json: @notice }
      end
  	end
  end

  # Book the rooms for particular dates and room type
  def book    
    dates = params[:book_room]
    @check_in = dates[:check_in].to_date
    @check_out = dates[:check_out].to_date        
    @room_type_id = dates[:room_type_id]
    @room_ids = params[:room_ids]        
    if @check_out > @check_in and !(@room_type_id.empty?)
      @rooms = Room.booked_room_ids(@room_type_id, @check_in, @check_out) 
      @room_nos = ""
      @room_ids = @room_ids.split(",") if @room_ids.is_a? String     
      @room_ids.each do |room|
        unless @rooms.include? room
          current_user_id = current_user.nil? ? nil : current_user.id
          Booking.create(user_id: current_user_id,room_id: room, room_type_id: @room_type_id, check_in: @check_in, check_out: @check_out)
          @room_nos << Room.find_by_id(room).number + "   "
        end
      end
      respond_to do |format|
        format.html
        format.json {render json: {room_no: @room_nos, check_in: @check_in, check_out: @check_out}}
      end
    else 
      @notice = "Check In Date is more than Check Out Date!!!"
      respond_to do |format|
        format.html {render "room_types/book"}
        format.json { render json: @notice }
      end      
    end
  end

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def history		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_type_helper.rb
module RoomTypeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">      
      <nav>
        <ul class="nav pull-right"> 
          <li><%= link_to "Home", root_path %></li>               
          <% if signed_in? %>            
            <li id="fat-menu" class="dropdown" style="padding-left: -30px;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">               
                <li>
                  <%= link_to "Booking History", history_user_path(current_user) %>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParityCubeAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
    	<div class="main_row">
    		<p class="alert"> <%= @alert %></p>
				<p id="notice" class="notice"><%= @notice %></p>				
				<%= yield %>      
    	</div>    	
      
    </div>	
</body>
</html>

app/views/room_types/book.html.erb
<div class="row">
  <%= form_for :room, url: rooms_index_path(room_type_id: params[:id]), :authenticity_token => true do |f| %>         
    
    <div class="col-xs-4 col-xx-12">
      <label class="form-title">Check In Date<span class="mandatory">*</span></label>
      <%= f.text_field :check_in, placeholder: "Check In", :class => "form-control date_pick", required: true, date: true %>
    </div>
    <div class="col-xs-4 col-xx-12">
      <label class="form-title">Check Out Date<span class="mandatory">*</span></label>
      <%= f.text_field :check_out, placeholder: "Check Out", :class => "form-control date_pick", required: true, date: true %>
    </div>
    
    <div class="form_btns">
      <%= f.submit "Next", :class => 'btn btn-primary' %>     
    </div>    
  <% end %>
</div>

<script type="text/javascript">
    $('.date_pick').datepicker();
</script>

app/views/room_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Room Types</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Total No. of Rooms</th>
      <th>Room Type</th>
      <th>Description</th>
      <th>Price / Night</th>      
      <th> Book a Room </th>      
    </tr>
  </thead>

  <tbody>
    <% @room_types.each do |rt| %>
      <tr>
        <td><%= rt.total_rooms %></td>
        <td><%= rt.name %></td>
        <td><%= rt.description %></td>
        <td><%= rt.price %></td>
        <td><%= link_to 'Book',  book_room_type_path(id: rt.id), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/book.html.erb
<h1>Booked Rooms <%= @room_nos %> Successfully</h1>

app/views/rooms/index.html.erb
<h1>Listing Room</h1>
<%= form_for :book_room, url: rooms_book_path, :authenticity_token => true do |f| %>
	<%= f.hidden_field :room_type_id, :value => @room_type_id %>
	<%= f.hidden_field :check_in, :value => @check_in %>
	<%= f.hidden_field :check_out, :value => @check_out %>
	<table class="table table-bordered">
	  <thead>
	    <tr>
	      <th>Checkbox</th>
	      <th>Room No.</th>      
	    </tr>
	  </thead>
	  <tbody>  	
	    <% @rooms.each do |rt| %>
	      <tr>
	        <td><%= check_box_tag 'room_ids[]', rt.id %></td>
	        <td><%= rt.number %></td>	        
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= f.submit "Book Rooms", :class => 'btn btn-primary' %> 
<% end %>

app/views/users/history.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Room Type</th>
      <th>Room No.</th>
      <th>Check In</th>
      <th>Check Out</th>
    </tr>
  </thead>
  <tbody>  	
    <% current_user.bookings.each do |booking| %>
      <tr>
        <td><%= booking.room_type.name %></td>
        <td><%= booking.room.number %></td>
        <td><%= booking.check_in %></td>
        <td><%= booking.check_out %></td>
      </tr>
    <% end %>
  </tbody>
</table>